variables:
  CONAN_REFERENCE: "vtk/8.0.1"
  CONAN_USERNAME: "sigth"
  CONAN_LOGIN_USERNAME: "sight"
  CONAN_CHANNEL: "stable"
  CONAN_STABLE_BRANCH_PATTERN: "stable/*"
  CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
  CONAN_ARCHS: x86_64

stages:
  - build

msvc2015:
  image: registry.lan.local:5000/docker-envdev-msvc2015:dev
  stage: build
  script:
    - python build.py
  tags:
    - docker
    - windows

msvc2017:
  image: registry.lan.local:5000/docker-envdev-msvc2017:dev
  stage: build
  script:
    - python build.py
  tags:
    - docker
    - windows

gcc-7:
  image: registry.lan.local:5000/docker-envdev:dev
  stage: build
  variables:
    CONAN_GCC_VERSIONS: "7"
  script:
    - export CC=/usr/bin/gcc-7
    - export CXX=/usr/bin/g++-7
    - python3 build.py

clang-6:
  image: registry.lan.local:5000/docker-envdev:dev
  stage: build
  variables:
    CONAN_CLANG_VERSIONS: "6.0"
  script:
    - export CC=/usr/bin/clang-6.0
    - export CXX=/usr/bin/clang++-6.0
    - python3 build.py